# to run: docker-compose run
#
#  sudo chown $(whoami):$(whoami) -R mediaserver-data/
#  docker inspect f08d746152c4 | grep "IPAddress" -> get ip from container
# 
# Create a .env file in the same folder as this file and change the variables.
# MOUNT_POINT=/tmp/
# VPN_PROVIDER=changeme
# VPN_CONFIG=changeme
# VPN_USERNAME=changeme
# VPN_PASSWORD=changeme
#
#
version: "2"

services:
  # transmission:
  #   image: haugene/transmission-openvpn
  #   container_name: transmission-openvpn
  #   restart: always
  #   ports:
  #     - "9091:9091"
  #   networks:
  #     - plexnet
  #   environment:
  #     - OPENVPN_PROVIDER=${VPN_PROVIDER}
  #     - OPENVPN_CONFIG=${VPN_CONFIG}
  #     - OPENVPN_USERNAME=${VPN_USERNAME}
  #     - OPENVPN_PASSWORD=${VPN_PASSWORD}
  #     - OPENVPN_OPTS="--inactive 3600 --ping 10 --ping-exit 60"
  #   volumes:
  #     - ${MOUNT_POINT}/transmission:/data
  #     - /etc/localtime:/etc/localtime:ro
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    restart: always
    ports:
      - "7878:7878"
    networks:
      - plexnet
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/London
    volumes:
      - ${MOUNT_POINT}/radarr-config:/config
      - ${MOUNT_POINT}/plex/data/movies:/movies
      - ${MOUNT_POINT}/qbittorrent/downloads:/downloads
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    restart: always
    ports:
      - "8989:8989"
    networks:
      - plexnet
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/London
    volumes:
      - ${MOUNT_POINT}/sonarr/config:/config
      - ${MOUNT_POINT}/plex/data/tv:/tv
      - ${MOUNT_POINT}/qbittorrent/downloads:/downloads
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    restart: always
    networks:
      - plexnet
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/London
    volumes:
      - ${MOUNT_POINT}/jackett/config:/config
      - ${MOUNT_POINT}/jackett/downloads:/downloads
    ports:
      - "9117:9117"
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    networks:
      - plexnet
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8081
    volumes:
      - ${MOUNT_POINT}/qbittorrent/config:/config
      - ${MOUNT_POINT}/qbittorrent/downloads:/downloads
    ports:
      - 8081:8081
      - 6881:6881
      - 6881:6881/udp
  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${MOUNT_POINT}/plex/config:/config
      - ${MOUNT_POINT}/plex/transcode:/transcode
      - ${MOUNT_POINT}/plex/data:/data
networks:
  plexnet:
    driver: bridge